# Definição de variáveis (ambiente “local” do REST Client)
@base_url = https://animated-telegram-jpvprvx9gpp3565q-8080.app.github.dev

### Inserir nova pessoa
POST {{ base_url }}/api/pessoas
Content-Type: application/json

{
  "nome": "Rafael",
  "idade": 34
}

### Listar todas as pessoas
GET {{ base_url }}/api/pessoas
Accept: application/json

### Buscar pessoa por ID
GET {{ base_url }}/api/pessoas/3
Accept: application/json

### Atualizar pessoa (PUT)
PUT {{ base_url }}/api/pessoas/1
Content-Type: application/json

{
  "nome": "Rafael Marinho",
  "idade": 35
}

### Remover pessoa (DELETE)
DELETE {{ base_url }}/api/pessoas/1
Accept: */*